spring:
  jmx:
    enabled: false

hono:
  client:
    host: localhost
    reconnectAttempts: 5
    hostnameVerificationRequired: false
    trustStorePath: trusted-certs.pem

connection:
  retryInterval: 1000

tenant:
  id: DEFAULT_TENANT
device:
  id: 4711

influxdb:
  url: http://localhost:8086
  db:
    name: devices
